%prod.quarkus.log.level=WARN
%prod.quarkus.swagger-ui.always-include=false
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${FF_DB_HOST}:${FF_DB_PORT}/${FF_DB_NAME}
