%dev.quarkus.http.port=8080
%dev.quarkus.log.level=INFO
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.swagger-ui.path=/q/swagger-ui
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.image-name=postgres:16-alpine
