%dev.quarkus.http.port=8080
%dev.quarkus.log.level=INFO
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.swagger-ui.path=/q/swagger-ui
%dev.quarkus.datasource.jdbc.url=jdbc:sqlite:${FF_DB_PATH:./data/dev.db}
