%test.quarkus.test.jvm-args=-Dnet.bytebuddy.experimental=true
%test.quarkus.test.continuous-testing=disabled
%test.quarkus.test.dev-mode=false
%test.quarkus.devui.enabled=false
%test.quarkus.datasource.jdbc.url=jdbc:sqlite::memory:
%test.ff.token.pepper=test-pepper
%test.ff.admin.username=admin
%test.ff.admin.password=admin
